import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Logo } from "@/components/layout/Logo";

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary via-primary/95 to-secondary">
      <div className="container max-w-4xl mx-auto px-4 py-8">
        <Button
          variant="ghost"
          className="text-white/80 hover:text-white hover:bg-white/10 mb-6"
          onClick={() => navigate("/")}
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to home
        </Button>

        <div className="bg-white rounded-lg shadow-xl p-8">
          <div className="flex justify-center mb-6">
            <Logo size="lg" />
          </div>

          <h1 className="text-3xl font-bold text-center mb-8">Terms of Service</h1>

          <div className="prose prose-sm max-w-none">
            <p className="text-muted-foreground mb-6">
              Last updated: February 12, 2026
            </p>

            <section className="mb-8">
              <h2 className="text-xl font-semibold mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing and using AFAQ ESG Navigator ("Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these Terms of Service, please do not use the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold mb-4">2. Description of Service</h2>
              <p>
                AFAQ provides ESG compliance assessment and disclosure report generation services for companies in the GCC region. Our platform helps organizations evaluate their ESG maturity against international frameworks including IFRS S1/S2, TCFD, GRI Standards, and regional requirements.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold mb-4">3. User Accounts</h2>
              <p>
                You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must immediately notify AFAQ of any unauthorized use of your account.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold mb-4">4. Educational Purpose Disclaimer</h2>
              <p className="text-destructive font-semibold">
                IMPORTANT: AFAQ ESG Navigator is an educational tool designed to provide insights and guidance on ESG compliance. The assessments, reports, and recommendations generated by our platform:
              </p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>Are NOT legal, financial, or regulatory advice</li>
                <li>Do NOT constitute professional audit or assurance services</li>
                <li>Should NOT be used as the sole basis for regulatory submissions</li>
                <li>Must be reviewed by qualified legal and compliance professionals before use</li>
              </ul>
              <p className="mt-4">
                Users are solely responsible for ensuring compliance with all applicable laws and regulations. Consult qualified professionals for official compliance requirements.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold mb-4">5. Data Accuracy</h2>
              <p>
                You are responsible for the accuracy and completeness of all information you provide to AFAQ. The quality of our assessments and reports depends on the quality of your input data. We are not liable for inaccuracies resulting from incomplete or incorrect information provided by users.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold mb-4">6. Intellectual Property</h2>
              <p>
                The AFAQ platform, including all content, features, and functionality, is owned by AFAQ and protected by international copyright, trademark, and other intellectual property laws. Reports generated using your company's data remain your property, but the underlying templates, methodologies, and algorithms are proprietary to AFAQ.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold mb-4">7. Limitation of Liability</h2>
              <p>
                AFAQ SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES resulting from your use of the Service, including but not limited to regulatory penalties, fines, or business losses arising from reliance on our assessments or reports.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold mb-4">8. Payment Terms</h2>
              <p>
                Paid services are billed in advance on a monthly or annual basis. All fees are non-refundable except as required by law. We reserve the right to modify pricing with 30 days' notice to existing subscribers.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold mb-4">9. Termination</h2>
              <p>
                We reserve the right to suspend or terminate your account if you violate these Terms of Service or engage in fraudulent, abusive, or illegal activity. Upon termination, your right to use the Service will immediately cease.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold mb-4">10. Governing Law</h2>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of the United Arab Emirates, without regard to its conflict of law provisions.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold mb-4">11. Changes to Terms</h2>
              <p>
                We reserve the right to modify these Terms at any time. We will notify users of material changes via email or through the Service. Your continued use of the Service after such modifications constitutes acceptance of the updated Terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold mb-4">12. Contact Information</h2>
              <p>
                For questions about these Terms of Service, please contact us at:
              </p>
              <p className="mt-2">
                Email: legal@afaq-esg.com<br />
                Address: [Company Address - To Be Added]
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
