import { DisclosureOutput, DisclosureSection, EvidenceReference, SustainabilityReport, ReportSection } from '@/types/compliance';

/**
 * Renders the disclosure narrative to a professional, standalone HTML document.
 */
export function renderDisclosureToHtml(disclosure: DisclosureOutput, language: 'en' | 'ar' = 'en'): string {
  const isRtl = language === 'ar';

  const sectionsHtml = disclosure.sections
    .map(section => `
      <section class="disclosure-section">
        <h2>${isRtl ? section.titleArabic || section.title : section.title}</h2>
        <div class="narrative">
          ${(isRtl ? section.narrativeArabic || section.narrative : section.narrative)
        .split('\n\n')
        .map(p => `<p>${p.replace(/\n/g, '<br>')}</p>`)
        .join('')}
        </div>
        ${section.dataPoints && section.dataPoints.length > 0 ? `
          <div class="data-points">
            <h3>Key Metrics</h3>
            <table>
              <thead>
                <tr>
                  <th>Indicator</th>
                  <th>Value</th>
                </tr>
              </thead>
              <tbody>
                ${section.dataPoints.map(dp => `
                  <tr>
                    <td>${isRtl ? dp.labelArabic || dp.label : dp.label}</td>
                    <td><strong>${dp.value}</strong></td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          </div>
        ` : ''}
      </section>
    `)
    .join('');

  const disclaimerHtml = disclosure.disclaimers
    .sort((a, b) => a.order - b.order)
    .map(d => `<p class="disclaimer"><strong>${(d.type || 'notice').toUpperCase()}:</strong> ${isRtl ? d.textArabic || d.text : d.text}</p>`)
    .join('');

  const html = `
<!DOCTYPE html>
<html lang="${language}" dir="${isRtl ? 'rtl' : 'ltr'}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ESG Disclosure Report - ${disclosure.generatedForCompany}</title>
    <style>
        :root {
            --primary: #0f172a;
            --secondary: #64748b;
            --accent: #2563eb;
            --bg: #ffffff;
            --text: #1e293b;
            --border: #e2e8f0;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            line-height: 1.6;
            color: var(--text);
            background: var(--bg);
            max-width: 800px;
            margin: 0 auto;
            padding: 40px 20px;
        }
        header {
            border-bottom: 2px solid var(--primary);
            margin-bottom: 40px;
            padding-bottom: 20px;
        }
        .meta {
            color: var(--secondary);
            font-size: 0.9rem;
            margin-top: 10px;
        }
        h1 { margin: 0; color: var(--primary); font-size: 2.2rem; }
        h2 { border-bottom: 1px solid var(--border); padding-bottom: 10px; margin-top: 40px; color: var(--primary); }
        h3 { font-size: 1.1rem; margin-top: 20px; color: var(--secondary); }
        p { margin-bottom: 1.2rem; }
        .disclosure-section { margin-bottom: 60px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { text-align: ${isRtl ? 'right' : 'left'}; padding: 12px; border-bottom: 1px solid var(--border); }
        th { background: #f8fafc; font-size: 0.8rem; text-transform: uppercase; color: var(--secondary); }
        .disclaimer { font-size: 0.8rem; color: var(--secondary); margin-top: 40px; padding: 20px; background: #f1f5f9; border-radius: 8px; }
        .footer { margin-top: 80px; text-align: center; border-top: 1px solid var(--border); padding-top: 20px; font-size: 0.8rem; color: var(--secondary); }
        
        @media print {
            body { padding: 0; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <header>
        <h1>${isRtl ? 'تقرير الإفصاح عن الاستدامة' : 'ESG Disclosure Report'}</h1>
        <div class="meta">
            <strong>${disclosure.generatedForCompany}</strong><br>
            ${isRtl ? 'السنة المالية' : 'Fiscal Year'}: ${disclosure.templateVersion || '2024'} | 
            ${isRtl ? 'تاريخ الإصدار' : 'Issue Date'}: ${new Date(disclosure.generatedAt).toLocaleDateString(language === 'ar' ? 'ar-AE' : 'en-US')}
        </div>
    </header>
 
    ${sectionsHtml}
 
    <div class="disclaimers">
      ${disclaimerHtml}
    </div>
 
    <div class="footer">
        Generated by AFAQ ESG Platform |
        Report ID: ${(disclosure.id || 'N/A').substring(0, 8)} |
        Authenticity Check: ${btoa(disclosure.id || 'N/A').substring(0, 12)}...
    </div>
</body>
</html>
  `;
  return html;
}

interface MetricItem {
  metricCode: string;
  title?: string;
  valueNumeric?: number | null;
  valueText?: string | null;
  valueBoolean?: boolean | null;
  unit?: string | null;
  category: string;
}

/**
 * Renders a detailed Evidence Appendix as an HTML document.
 */
export function renderEvidenceAppendixToHtml(
  disclosure: DisclosureOutput,
  metrics: MetricItem[],
  narratives: Record<string, string>,
  language: 'en' | 'ar' = 'en'
): string {
  const isRtl = language === 'ar';

  const metricsHtml = metrics.map(m => `
    <tr>
      <td><code>${m.metricCode}</code></td>
      <td>${m.title || m.metricCode}</td>
      <td><strong>${m.valueNumeric ?? m.valueText ?? m.valueBoolean ?? 'N/A'} ${m.unit || ''}</strong></td>
      <td>${m.category}</td>
    </tr>
  `).join('');

  const html = `
<!DOCTYPE html>
<html lang="${language}" dir="${isRtl ? 'rtl' : 'ltr'}">
<head>
    <meta charset="UTF-8">
    <title>Evidence Appendix - ${disclosure.generatedForCompany}</title>
    <style>
        body { font-family: sans-serif; color: #334155; max-width: 1000px; margin: 40px auto; padding: 0 20px; }
        h1 { color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 30px; }
        th, td { text-align: left; padding: 12px; border: 1px solid #e2e8f0; font-size: 14px; }
        th { background: #f8fafc; }
        code { background: #f1f5f9; padding: 2px 4px; border-radius: 4px; font-size: 12px; }
        .section-title { margin-top: 40px; background: #f1f5f9; padding: 10px; font-weight: bold; }
    </style>
</head>
<body>
    <h1>Evidence Appendix (Traceability Matrix)</h1>
    <p>Company: ${disclosure.generatedForCompany} | Generated: ${new Date(disclosure.generatedAt).toLocaleString()}</p>
    
    <div class="section-title">Quantitative Metrics</div>
    <table>
        <thead>
            <tr>
                <th>Code</th>
                <th>Description</th>
                <th>Value</th>
                <th>Category</th>
            </tr>
        </thead>
        <tbody>
            ${metricsHtml}
        </tbody>
    </table>

    <div class="section-title">Qualitative Narratives</div>
    <div style="margin-top: 20px;">
        ${Object.keys(narratives).map(key => `
            <div style="margin-bottom: 20px; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px;">
                <div style="font-weight: bold; margin-bottom: 5px; color: #64748b; font-size: 12px;">SOURCE: ${(key || 'unknown').toUpperCase()}</div>
                <div style="font-size: 14px;">${narratives[key]}</div>
            </div>
        `).join('')}
    </div>

    <footer style="margin-top: 60px; font-size: 12px; color: #94a3b8; text-align: center;">
        This appendix accompanies ESG Disclosure Report ${(disclosure.id || 'N/A').substring(0, 8)}.
    </footer>
</body>
</html>
  `;
  return html;
}

/**
 * Renders a full Sustainability Report to a professional, GRI-style HTML document.
 */
export function renderSustainabilityReportToHtml(
  report: SustainabilityReport,
  language: 'en' | 'ar' = 'en'
): string {
  const isRtl = language === 'ar';

  const sectionIcons: Record<string, string> = {
    executive_summary: '📋',
    environmental: '🌿',
    social: '👥',
    governance: '🏛️',
    methodology: '📖',
    data_annex: '📊',
  };

  const sectionColors: Record<string, string> = {
    executive_summary: '#475569',
    environmental: '#059669',
    social: '#7c3aed',
    governance: '#2563eb',
    methodology: '#d97706',
    data_annex: '#6b7280',
  };

  const renderMetrics = (metrics: ReportSection['metrics']) => {
    if (!metrics || metrics.length === 0) return '';
    return `
      <div class="metrics-grid">
        ${metrics.map(m => `
          <div class="metric-card">
            <div class="metric-code">${m.code}</div>
            <div class="metric-name">${m.name}</div>
            <div class="metric-value">${m.value}${m.unit ? ` <span class="metric-unit">${m.unit}</span>` : ''}</div>
          </div>
        `).join('')}
      </div>
    `;
  };

  const renderDisclosures = (disclosures: ReportSection['disclosures']) => {
    if (!disclosures || disclosures.length === 0) return '';
    return `
      <div class="disclosures-section">
        <h4>Disclosures Addressed</h4>
        <div class="disclosure-tags">
          ${disclosures.map(d => `
            <span class="disclosure-tag ${d.status}">${d.framework} ${d.code}</span>
          `).join('')}
        </div>
      </div>
    `;
  };

  const sectionsHtml = report.sections
    .sort((a, b) => a.order - b.order)
    .map(section => `
      <section class="report-section" style="--section-color: ${sectionColors[section.type] || '#475569'}">
        <div class="section-header">
          <span class="section-icon">${sectionIcons[section.type] || '📄'}</span>
          <div>
            <h2>${section.title}</h2>
            ${section.titleArabic && isRtl ? `<p class="title-arabic">${section.titleArabic}</p>` : ''}
          </div>
        </div>
        <div class="narrative">
          ${section.narrative
            .split('\n\n')
            .map(p => `<p>${p.replace(/\n/g, '<br>')}</p>`)
            .join('')}
        </div>
        ${renderMetrics(section.metrics)}
        ${renderDisclosures(section.disclosures)}
      </section>
    `)
    .join('');

  const dataAnnexHtml = report.dataAnnex.length > 0 ? `
    <section class="data-annex">
      <h2>📊 Data Annex - Quantitative Disclosures</h2>
      <p class="annex-intro">The following table presents all quantitative metrics disclosed in this report in GRI-compatible format.</p>
      <table class="annex-table">
        <thead>
          <tr>
            <th>Code</th>
            <th>Metric</th>
            <th>Value</th>
            <th>Unit</th>
            <th>Section</th>
            <th>Disclosure Ref</th>
          </tr>
        </thead>
        <tbody>
          ${report.dataAnnex.map(row => `
            <tr>
              <td><code>${row.metricCode}</code></td>
              <td>${row.metricName}</td>
              <td class="value-cell"><strong>${typeof row.value === 'number' ? row.value.toLocaleString() : row.value}</strong></td>
              <td>${row.unit || '-'}</td>
              <td>${row.reportSection}</td>
              <td>${row.disclosureRef || '-'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </section>
  ` : '';

  const disclosureStatsHtml = `
    <section class="disclosure-stats">
      <h2>📋 Disclosure Index</h2>
      <div class="stats-grid">
        <div class="stat-card addressed">
          <div class="stat-value">${report.addressedDisclosures}</div>
          <div class="stat-label">Addressed</div>
        </div>
        <div class="stat-card partial">
          <div class="stat-value">${report.partialDisclosures}</div>
          <div class="stat-label">Partial</div>
        </div>
        <div class="stat-card omitted">
          <div class="stat-value">${report.omittedDisclosures}</div>
          <div class="stat-label">Omitted</div>
        </div>
        <div class="stat-card total">
          <div class="stat-value">${Math.round((report.addressedDisclosures / Math.max(report.totalDisclosures, 1)) * 100)}%</div>
          <div class="stat-label">Completion</div>
        </div>
      </div>
    </section>
  `;

  const html = `
<!DOCTYPE html>
<html lang="${language}" dir="${isRtl ? 'rtl' : 'ltr'}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sustainability Report ${report.reportingYear} - ${report.companyName}</title>
    <style>
        :root {
            --primary: #0f172a;
            --secondary: #64748b;
            --accent: #2563eb;
            --bg: #ffffff;
            --text: #1e293b;
            --border: #e2e8f0;
            --success: #059669;
            --warning: #d97706;
            --danger: #dc2626;
        }
        * { box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            line-height: 1.7;
            color: var(--text);
            background: var(--bg);
            max-width: 900px;
            margin: 0 auto;
            padding: 60px 40px;
        }
        header {
            text-align: center;
            padding-bottom: 40px;
            margin-bottom: 40px;
            border-bottom: 3px solid var(--primary);
        }
        .company-name {
            font-size: 2.5rem;
            font-weight: 700;
            color: var(--primary);
            margin: 0;
        }
        .company-name-arabic {
            font-size: 1.8rem;
            color: var(--secondary);
            margin-top: 8px;
        }
        .report-meta {
            margin-top: 20px;
            font-size: 1rem;
            color: var(--secondary);
        }
        .score-badge {
            display: inline-block;
            background: linear-gradient(135deg, var(--accent), #1d4ed8);
            color: white;
            padding: 15px 30px;
            border-radius: 12px;
            margin-top: 25px;
            font-size: 1.2rem;
        }
        .score-badge strong {
            font-size: 2rem;
            display: block;
        }

        .report-section {
            margin: 50px 0;
            padding: 30px;
            background: #fafafa;
            border-radius: 12px;
            border-left: 4px solid var(--section-color, var(--primary));
        }
        .section-header {
            display: flex;
            align-items: center;
            gap: 15px;
            margin-bottom: 20px;
        }
        .section-icon {
            font-size: 2rem;
        }
        .section-header h2 {
            margin: 0;
            color: var(--primary);
            font-size: 1.5rem;
        }
        .title-arabic {
            margin: 5px 0 0;
            color: var(--secondary);
            font-size: 1.1rem;
        }
        .narrative p {
            margin-bottom: 1.2rem;
            text-align: justify;
        }

        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
            gap: 15px;
            margin: 25px 0;
            padding-top: 20px;
            border-top: 1px solid var(--border);
        }
        .metric-card {
            background: white;
            padding: 15px;
            border-radius: 8px;
            border: 1px solid var(--border);
        }
        .metric-code {
            font-family: monospace;
            font-size: 0.75rem;
            color: var(--secondary);
        }
        .metric-name {
            font-size: 0.9rem;
            margin: 5px 0;
        }
        .metric-value {
            font-size: 1.3rem;
            font-weight: 700;
            color: var(--primary);
        }
        .metric-unit {
            font-size: 0.8rem;
            font-weight: normal;
            color: var(--secondary);
        }

        .disclosures-section {
            margin-top: 20px;
            padding-top: 15px;
            border-top: 1px solid var(--border);
        }
        .disclosures-section h4 {
            font-size: 0.8rem;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            color: var(--secondary);
            margin-bottom: 10px;
        }
        .disclosure-tags {
            display: flex;
            flex-wrap: wrap;
            gap: 8px;
        }
        .disclosure-tag {
            font-size: 0.75rem;
            padding: 4px 10px;
            border-radius: 4px;
            background: #e2e8f0;
            color: var(--text);
        }
        .disclosure-tag.addressed { background: #d1fae5; color: #065f46; }
        .disclosure-tag.partial { background: #fef3c7; color: #92400e; }
        .disclosure-tag.omitted { background: #fee2e2; color: #991b1b; }

        .disclosure-stats {
            margin: 50px 0;
            padding: 30px;
            background: linear-gradient(135deg, #f8fafc, #f1f5f9);
            border-radius: 12px;
        }
        .disclosure-stats h2 {
            margin: 0 0 20px;
            color: var(--primary);
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
        }
        .stat-card {
            text-align: center;
            padding: 20px;
            border-radius: 8px;
            background: white;
        }
        .stat-card.addressed { border-bottom: 3px solid var(--success); }
        .stat-card.partial { border-bottom: 3px solid var(--warning); }
        .stat-card.omitted { border-bottom: 3px solid var(--danger); }
        .stat-card.total { border-bottom: 3px solid var(--accent); }
        .stat-value {
            font-size: 2rem;
            font-weight: 700;
            color: var(--primary);
        }
        .stat-label {
            font-size: 0.8rem;
            color: var(--secondary);
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .data-annex {
            margin: 50px 0;
        }
        .data-annex h2 {
            color: var(--primary);
            margin-bottom: 10px;
        }
        .annex-intro {
            color: var(--secondary);
            margin-bottom: 20px;
        }
        .annex-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.9rem;
        }
        .annex-table th, .annex-table td {
            padding: 12px 10px;
            border: 1px solid var(--border);
            text-align: ${isRtl ? 'right' : 'left'};
        }
        .annex-table th {
            background: #f8fafc;
            font-weight: 600;
            font-size: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            color: var(--secondary);
        }
        .annex-table code {
            background: #f1f5f9;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 0.8rem;
        }
        .value-cell {
            text-align: right;
        }

        footer {
            margin-top: 60px;
            padding-top: 30px;
            border-top: 1px solid var(--border);
            text-align: center;
            color: var(--secondary);
            font-size: 0.85rem;
        }
        footer p { margin: 5px 0; }

        @media print {
            body { padding: 20px; }
            .report-section { break-inside: avoid; }
            .data-annex { break-before: page; }
        }
    </style>
</head>
<body>
    <header>
        <h1 class="company-name">${report.companyName}</h1>
        ${report.companyNameArabic ? `<p class="company-name-arabic">${report.companyNameArabic}</p>` : ''}
        <div class="report-meta">
            Sustainability Report ${report.reportingYear} • ${report.jurisdiction}
        </div>
        <div class="score-badge">
            <strong>${Math.round((report.addressedDisclosures / Math.max(report.totalDisclosures, 1)) * 100)}%</strong>
            ESG Disclosure Score
        </div>
    </header>

    ${sectionsHtml}

    ${disclosureStatsHtml}

    ${dataAnnexHtml}

    <footer>
        <p>Generated on ${new Date(report.generatedAt).toLocaleDateString(language === 'ar' ? 'ar-AE' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        <p>Template Version ${report.templateVersion} • Report ID: ${(report.id || 'N/A').substring(0, 8)}</p>
        <p>Prepared using AFAQ ESG Platform in accordance with ${
          report.jurisdiction === 'UAE' ? 'ADX ESG Disclosure Guidelines' :
          report.jurisdiction === 'KSA' ? 'Tadawul ESG Disclosure Guidelines' :
          'QSE Sustainability Reporting Guidelines'
        }</p>
    </footer>
</body>
</html>
  `;
  return html;
}
